# Generated by Django 5.0.4 on 2024-05-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('new', models.BooleanField(default=False)),
                ('added', models.DateTimeField()),
            ],
            options={
                'ordering': ['added'],
            },
        ),
        migrations.DeleteModel(
            name='Item_rest',
        ),
    ]
